# image: nikolaik/python-nodejs:python3.7-nodejs12
image: docker

cache:
  paths:
    - node_modules/

before_script:
  - docker info

build-stg: 
  stage: build
  script: 
    - cd imgscoring-svc
    - docker build -t imgscoring-svc .
  only:
    - stg

# deploy-stg:
#   stage: deploy
#   script:
#     - cd imgscoring-svc
#     - python -m venv venv
#     - source venv/bin/activate
#     - npm install
#     - npx serverless package -s stg
#     - npx serverless deploy -s stg
#   only:
#     - stg
