image: node:12

cache:
  paths:
  - node_modules/

deploy-stg:
  stage: deploy
  script:
    - cd imgscoring-svc
    - npm install
    # - python -m venv
    # - venv/bin/activate
    - npx serverless package -s stg
    - npx serverless deploy -s stg
  only:
    - stg
